### ISSUE TITLE
Unable to watch any movie using Real-Debrid

### ISSUE THREAD

**Issue by Nigel1992** [jsergio123/script.module.resolveurl#328]
Hello,

I am suddenly unable to watch any movie using Real-Debrid.
I tried clearing Function Cache, as well as Re-authorizing my Real-Debrid.
Here's a link to the error: https://i.imgur.com/jX1tUiB.png
Receiving this error on a fresh install as well on a different machine.
There's nothing in the LOG, but I am willing to send HTTP Debug info to @jsergio123 only.
Getting the same error when using URL Resolver, instead of ResolveURL.
I feel like Real Debrid is either having issues, or updated their API.
ResolveURL version: 5.0.42
Latest Kodi with Exodus and Venom.

**Comment by Gujal00** [comment]
Sorry, screenshots are of no use
And Addon support is not provided by here.
If you have a url that should be resolved by ResolveURL but not working, provide it. Otherwise raise an issue with the relevant addon providers.
This is not a Support site for watching movies with other addons

Real Debrid api endpoint hasnt changed and is still https://api.real-debrid.com/rest/1.0/unrestrict/link
