### ISSUE TITLE
Playtube

### ISSUE THREAD

**Issue by dobbelina** [jsergio123/script.module.resolveurl#371]
https://github.com/dobbelina/repository.dobbelina/issues/284#issuecomment-691214185
As I was looking into this, I noticed the errors when selecting Playtube. This has to do with the plugin within the ResolveURL addon. Once the update gets pushed and you want to fix this yourself, browse to .kodi/addons/script.module.resolveurl/lib/resolveurl/plugins and select playtube.py to edit. Scroll down to the last line "return self._default_get_url(host,media_id,template='https://{host}/embed-{media_id}.html')" Remove "embed-", it should now be "return self._default_get_url(host,media_id,template='https://{host}/{media_id}.html')" & save the file. You should now be able to play from Playtube.

**Comment by Gujal00** [comment]
@dobbelina 
I dont see an issue with the current plugin, if there is some playtube embed not working with the resolver, please share so that I can take a look
update: Okay I see that sometimes it complains with `Video embed restricted for this domain`. Have improved the code to handle that correctly.
Fixed in https://github.com/jsergio123/script.module.resolveurl/commit/07b2249f390ba20f8c7588422b8211ca67cebf6d

**Comment by dobbelina** [comment]
It still errors out with "Resolve failed".
This edit to the last line and it works:
`return self._default_get_url(host,media_id,template='https://{host}/{media_id}.html')`

**Comment by dobbelina** [comment]
Issue resolved, i forgot the helpers.py file.
Thanks for the fix! 👍
