### ISSUE TITLE
ResolveURL fails to resolve streams from plugins added with "add_plugin_dirs"

### ISSUE THREAD

**Issue by Twilight0** [jsergio123/script.module.resolveurl#408]
I 've written the euronews plugin for internal use, you can have a look at it here: [https://pastebin.com/CA8xqyaY](https://pastebin.com/CA8xqyaY)

I am loading this plugin with "add_plugin_dirs" and I can see that mentioned plugin is successfully loaded into the list of "relevant resolvers"

    2020-12-27 15:59:28.825 T:140014186395392   DEBUG: ResolveURL: Loaded <module 'euronews' from '/home/twilight/.kodi/addons/plugin.video.AliveGR/resources/lib/resolvers/plugins/euronews.pyo'> as euronews from euronews.py

Then, I am getting this into the log: 

    2020-12-27 15:59:28.838 T:140014186395392   DEBUG: ResolveURL: Relevant Resolvers: []

**HostedMediaFile(url).valid_url()** also returns False.

Initially I tested the plugin by simply copying and pasting it within the primary "plugins" dir in the resolveurl module tree.
I was wondering that I might be doing something wrong on my part. Test urls:

https://gr.euronews.com/video/2020/12/27/xekinisan-oi-emvoliasmoi-stin-evropi
https://gr.euronews.com/2020/12/23/o-mesi-espase-to-rekor-tou-pele
https://gr.euronews.com/live

**Comment by groggyegg** [comment]
Did you enable the plugin? This is a similar problem I had before. By adding directory through add_plugin_dirs, requires you to enable the plugins before it can be used.

This code is a simple way to enable the plugins:

```
@classmethod
def _is_enabled(cls):
    return True
```

This seems to be a bug related to the class ResolveUrl where it tries to retrieve the enabled value from the settings, and since the setting does not exist it returns a false value.

**Comment by Twilight0** [comment]
Indeed it worked, thank you. Closing this issue.
