### ISSUE TITLE
[Request] Create a repo for 'urlresolver'

### ISSUE THREAD

**Issue by burekas7** [jsergio123/script.module.resolveurl#418]
Hi @Gujal00 ,

Can you make a repo also for 'urlresolver' as the as you created for 'resolveurl'?
Currently you have only this one: repository.resolveurl-1.0.0

Or even better a create a repo that will include both 'resolveurl' and 'urlresolver', it will be perfect.

---

@jsergio123 
btw, Your repo doesn't include the last 'urlresolver' version that exist in Gujal00 repo.
It shows the last version as "5.0.38" while the last one is "5.1.22".

In addition the same request here, if you could also add the last version (Currently 5.1.20) to your repo as well.

---

Thanks you both.

**Comment by Gujal00** [comment]
I maintain resolveurl and so i have that in my repository. Why would I include something that I dont code or maintain?
@jsergio123 retired last year and has nothing to do with resolveurl day to day stuff anymore. His repo stands at the last version he worked on and released.

**Comment by burekas7** [comment]
@Gujal00 

But as you can see here:
https://github.com/tvaddonsco/script.module.urlresolver

Your nickname is there, so this is why I asked:
![image](https://user-images.githubusercontent.com/13424257/105094300-c0c5df00-5aac-11eb-9d92-5d7d4480dcd5.png)

And I mention @jsergio123 because the last resolveurl is updated here:
https://github.com/jsergio123/script.module.resolveurl

**Comment by Gujal00** [comment]
Yeah they take my code and make their releases. I dont do anything there, I havent committed to that repo in a longtime.
urlresolver original developers eldorado and tknorris retired in 2017. tvaddonsco have not writtten a single line of code since then and have just been taking the code from resolveurl and releasing it. It is silly if any addon is still using urlresolver when the developer retired 4 years ago.
