### ISSUE TITLE
Will there be a release for Kodi 19 Matrix?

### ISSUE THREAD

**Issue by dumbo0001** [jsergio123/script.module.resolveurl#433]
I am wondering if there will be a release compatible with Kodi 19 (Matrix).
At this moment we need to uncomment  `<!-- <import addon="xbmc.python" version="3.0.0" /> -->` to be able to install in Kodi 19.

**Comment by dumbo0001** [comment]
Never mind.. Manual installing the addon works. Not sure about auto-update though..

**Comment by Gujal00** [comment]
Install ResolveURL repo from here https://raw.githubusercontent.com/Gujal00/smrzips/master/zips/repository.resolveurl/repository.resolveurl-1.0.0.zip
And then you will get auto updates. Because of Kodi19 limitation, you have to update your resolveurl manually from the repo the first time, then resolveurl repo will be marked as the origin repo for resolveurl. After this all subsequent updates will be automatic
