### ISSUE TITLE
NitroFlare needs to be droped 

### ISSUE THREAD

**Issue by SerpentDrago** [jsergio123/script.module.resolveurl#83]
RD no longer Supports NitroFlare 

https://real-debrid.com/compare

Or add option to disable in settings ( i couldn't find it , or find the py file )

**Comment by Gujal00** [comment]
If real-debrid doesn't support Nitroflare they should reflect it by removing nitroflare from their regex. 
`https://api.real-debrid.com/rest/1.0/hosts/regex`
ResolveUrl just uses whatever regex RD provides and cannot do anything otherwise about it.
Please raise the issue with RD tasking them to remove Nitroflare from their regex. This is still there in the regex that RD provide
`"/(http|https):\\/\\/(\\w+\\.)?nitroflare\\.com\\/([^( |\"|'|>|<|\\r\\n\\|\\r|\\n|:|$)]+)/"`

**Comment by SerpentDrago** [comment]
Support ticket sent to RD . 

Thanks for the info !
